//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiStatsAppV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class H15_SIM_E03Entities : DbContext
    {
        public H15_SIM_E03Entities()
            : base("name=H15_SIM_E03Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<CentreDeSkis> CentreDeSkis { get; set; }
        public virtual DbSet<Descentes> Descentes { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Saisons> Saisons { get; set; }
        public virtual DbSet<Sorties> Sorties { get; set; }
    }
}
