//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiStatsAppV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saisons
    {
        public Saisons()
        {
            this.Sorties = new HashSet<Sorties>();
        }
    
        public int SaisonId { get; set; }
        public System.DateTime Annee { get; set; }
    
        public virtual ICollection<Sorties> Sorties { get; set; }
    }
}
